-- 코드를 입력하세요
WITH TOTAL_SALE AS(
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
)


SELECT U.USER_ID, U.NICKNAME, T.TOTAL_SALES
FROM USED_GOODS_USER AS U JOIN TOTAL_SALE AS T
ON U.USER_ID = T.WRITER_ID
WHERE T.TOTAL_SALES>=700000
ORDER BY T.TOTAL_SALES ASC;