-- 코드를 작성해주세요

WITH TOTAL_SCORE AS(
    SELECT EMP_NO, SUM(SCORE) AS SCORE FROM HR_GRADE GROUP BY EMP_NO)
    
SELECT T.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E JOIN TOTAL_SCORE AS T
ON E.EMP_NO = T.EMP_NO
ORDER BY T.SCORE DESC
LIMIT 1;